const salario = document.querySelector("#salario");
const sueldos = document.querySelector("#sueldos");
const promedio = document.querySelector("#promedio");
const mediana = document.querySelector("#mediana");
const moda = document.querySelector("#moda");
const btnEnviar = document.querySelector("#btnEnviar");
btnEnviar.addEventListener("click", enviarSueldo);
const btnCalcularPromedio = document.querySelector("#btnCalcularPromedio");
const btnCalcularMediana = document.querySelector("#btnCalcularMediana");
const btnCalcularModa = document.querySelector("#btnCalcularModa");
btnCalcularPromedio.addEventListener("click", fnCalcularPromedio);
btnCalcularMediana.addEventListener("click", fnCalcularMediana);
btnCalcularModa.addEventListener("click", fnCalcularModa);